### ISSUE TITLE
Possibly destructive header manipulation

### ISSUE THREAD

**Issue by oliversalzburg** [danialfarid/ng-file-upload#1134]
I'm not sure if this is an issue that needs to be addressed in ng-file-upload, but it just caused me a lot of trouble.

In https://github.com/danialfarid/ng-file-upload/blob/master/src/upload.js#L267 the passed `headers` object has the `Content-Type` member set to `undefined`.

We were passing in a header object that is used in several places in our application. I noticed that after I uploaded an image, many API requests would break for some weird reason. This was because the `Content-Type` was now set to `text-plain` on *all* API requests and `body-parser` would no longer parse the JSON payloads :\

A simple `angular.copy()` or `_.clone()` resolved the issue, but maybe you want to address this also in ng-file-upload itself.

**Comment by jimmy-tfp** [comment]
I had this issue as well

**Comment by danialfarid** [comment]
I don't see how setting a header in upload config options would affect other api calls and how angular copy would fix it, could you elaborate more or post some code or jsfiddle sample?

**Comment by oliversalzburg** [comment]
@danialfarid You are manipulating the `headers` object that is passed into the `Upload` service. If that headers object is used elsewhere, this is a possibly destructive operation.

Making a copy of the object and passing the copy into the `Upload` service resolves the issue, because you then no longer care about destructive operations.

**Comment by oliversalzburg** [comment]
Here is an example: http://jsfiddle.net/xxo3sk41/122/

`api` would be our service which we augmented to always use our `Authorization` header. We let `Upload` use the same `headers` object, so it can share the authorization data. But it will set `Content-Type` to `undefined`, which will cause future API calls to fail as explained above.

**Comment by danialfarid** [comment]
Fixed at version 10.1.0

**Comment by oliversalzburg** [comment]
Awesome :+1: :)

**Comment by gen4sp** [comment]
I same  issue. 
after uploading a file, all post requests become having a "text/plain" request content-type.
And server couldn't recognize data now. 

What is a possible reason? How i can fix it?

**Comment by gen4sp** [comment]
Yes, after uploading file 
header object has {Content-Type: undefined}

version "ng-file-upload": "^12.0.4",

**Comment by oliversalzburg** [comment]
I think there has been a regression (or the issue was never actually fixed) and this issue is back. We're seeing it in 12.2.13
