### ISSUE TITLE
Failed to execute 'setRequestHeader' on 'XMLHttpRequest'

### ISSUE THREAD

**Issue by Donniewiko** [danialfarid/ng-file-upload#812]
I was receiving this error also. Just posting the issue and ~~solution~~ workaround here.

In my case the error occured when i used the module: https://github.com/jpillora/xdomain

Haven't got time to investigate this so i just removed the xdomain script for now.

**Comment by Donniewiko** [comment]
I located the source of the issue and opened a support ticket on https://github.com/jpillora/xdomain/issues/157

**Comment by danialfarid** [comment]
Fixed in version 5.0.9
Make sure you load ng-file-upload before xdomain.

**Comment by Donniewiko** [comment]
Hi Danial, this fixes the error, much appreciated.

Out of curiosity, i checked your push and i noticed that you changed the order of files, which resulted in loads of changed lines. Was there anything else you did that fixed this? Because, as i recall, i have played alot with the loading order in our app, but that didn't fixed it, now it does.

Thanks again.

**Comment by danialfarid** [comment]
The order of files were supposed to be like that but I think at version 5.0.0 I accidentally changed the order when I was refactoring the grunt file.
As for the fix, I moved the part that changes the prototype of XMLHttpRequest outside the angular service function and in the root, so it would be executed right away so that xdomain would pick up the already modified XMLHttpRequest. Before that code was inside angular service so it would be run after xdoamin scripts was loaded.

**Comment by madmod** [comment]
I know this is old, but in case anyone else runs into this issue again and searches for this it can be fixed easily by doing the following.

```html
<!-- xdomain should always be loaded first according to its documentation. -->
<script src="//cdn.rawgit.com/jpillora/xdomain/0.7.4/dist/xdomain.min.js"></script>
<script>
  // Revert the XMLHttpRequest to the original from before xdomain (xhook) modified it.
  xhook.disable();
</script>
<script src="somewhere/ng-file-upload.min.js"></script>
<script>
  // Re-enable the xdomain (xhook) XMLHttpRequest.
  xhook.enable();
</script>
```

This might cause some issues if you attempt to make a cross domain request before xhook is re-enabled, but in my case it works great.

**Comment by ranouf** [comment]
I just downloaded the version x64 1.16.1 and the error is still there:
![image](https://user-images.githubusercontent.com/1764519/30867034-d7815ff4-a2a8-11e7-9ca9-fa58f2ba6aae.png)

Is there a fix?

**Comment by ayushsuccessive** [comment]
oooooooooooooooooo
